kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
data:
  sync.yaml: |                                 
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldaps://estesdca01.estes.us.dom:3269                  
    insecure: false
    bindDN: OU=OCP4,OU=Linux,OU=Security
      Groups,OU=Enterprise Production,DC=estes,DC=us,DC=domm         
    bindPassword:
      file: "/etc/secrets/bindPassword"
    ca: /etc/ldap-ca/ca.crt
    rfc2307:                                   
      groupsQuery:
        baseDN: "OU=OCP4,OU=Linux,OU=Security
      Groups,OU=Enterprise Production,DC=estes,DC=us,DC=domm"  
        scope: sub
        filter: "(objectClass=groupOfMembers)"
        derefAliases: never
        pageSize: 0
      groupUIDAttribute: dn
      groupNameAttributes: [ cn ]
      groupMembershipAttributes: [ member ]
      usersQuery:
        baseDN: "OU=OCP4,OU=Linux,OU=Security
      Groups,OU=Enterprise Production,DC=estes,DC=us,DC=domm"   
        scope: sub
        derefAliases: never
        pageSize: 0
      userUIDAttribute: dn
      userNameAttributes: [ uid ]
      tolerateMemberNotFoundErrors: false
      tolerateMemberOutOfScopeErrors: false